[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2



# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/mattia-de-filippo-467655153/"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/defilippomattia/"
    weight = 2
